workbook/dict/urls.py
from django.urls import path
from . import views

# 正在部署的应用名称

app_name = 'dict'

urlpatterns = [
    # path 函数将url映射到视图view
    # 接口1：访问全部字典
    path('word-list/',views.word_list,name = 'word_list'),
    path('word-detail/<int:id>/',views.word_detail,name = 'word_detail'),
    path('translate/',views.translate,name = 'translate'),
    path('search/',views.search,name = 'search'),
    path('deeplearning/',views.deeplearning,name = 'deeplearning'),
    path('insert/',views.insert,name = 'insert'),
    path('order/',views.order,name = 'order'),
]

workbook/workbook/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 配置 dict 的 url
    path('dict/',include('dict.urls',namespace = 'dict')),
]

workbook/dict/models.py
from django.db import models
from django.utils import timezone

class WordColumn(models.Model):
    """
    单词的分类
    """
    # 分类标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

# 单词数据模型
class Word(models.Model):
    # 单词拼写,最长为100
    spell = models.CharField(max_length = 100)
    # 单词词性
    # nature = models.CharField(max_length = 10)
    # 过去式
    past = models.CharField(max_length = 100,default = '')
    # 过去分词
    pasted = models.CharField(max_length = 100,default = '')
    # 现在分词
    nowing = models.CharField(max_length = 100,default = '')
    # 名词复数
    fushu = models.CharField(max_length = 200,default = '')
    # 词性+翻译
    translation = models.CharField(max_length = 200,default = '')
    # 典型例句
    example = models.TextField()
    # 创建时间
    created = models.DateTimeField(default = timezone.now)
    # 修改时间
    # updated = models.DateTimeField(auto_now=True)

    # 单词与分类的 “一对多” 外键
    column = models.ForeignKey(
        WordColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        # related_name='column'
    )
    
    # 内部类 class Meta
    class Meta:
        ordering = ('-created',)

    # 定义当前调用对象的__str__方法时候返回spell
    def __str__(self):
        return self.spell

# 用户提交的翻译内容
class UserInput(models.Model):
    # 用户提交的中文
    userInput = models.CharField(max_length = 100)

workbook/dict/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import UserInput,Word

# 用户提交的表单
class UserInputForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = UserInput
        # 定义表单包含的字段
        fields = ('userInput',)

# 用户搜索表单
# class UserSearchForm(forms.ModelForm):
#     class Meta:
#         model = UserSearch
#         fields = ('userInput',)

# 用户提交的新增
class UserInsert(forms.ModelForm):
    class Meta:
        model = Word
        fields = ('spell','past','pasted','nowing','fushu','translation','example',)

workbook/dict/views.py
from django.shortcuts import render,redirect
from .models import Word,WordColumn
# 爬虫相关
import requests
import json
# 引入表单
from .forms import UserInputForm,UserInsert
# 引入分页模块
from django.core.paginator import Paginator
# 导入 HttpResponse 模块
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from . import models

# 单词列表
def word_list(request):
    # 取出所有的 word
    word_list = Word.objects.all()
    # 每页显示10个单词
    paginator = Paginator(word_list, 3)
    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将相应的页码返回给words
    words = paginator.get_page(page)
    # 返回的对象做成字典
    context = {'words':words}
    # 载入模板 将 context返回
    return render(request,'word/list.html',context)

# 单词详情
def word_detail(request,id):
    # 提取出相应的单词
    word = Word.objects.get(id = id)
    # 需要传递给模板的对象
    context = {'word':word}
    # 返回
    return render(request,'word/detail.html',context)

# 翻译模块
def translate(request):
    # 提取用户提交得数据
    userInput = request.POST.get('userInput')
    print(userInput)

    if userInput is None:
        return render(request,'word/translate.html')
    else:
        # 爬虫代码
        url = 'http://fanyi.youdao.com/translate?smartresult=dict&smartresult=rule'
        Form_data = {
            'i':'',
            'from':'AUTO',
            'to':'AUTO',
            'smartresult':'dict',
            'client':'fanyideskweb',
            'salt':'15893888011282',
            'sign':'2e7b48b2843fef18430425b7266e367d',
            'ts':'1589388801128',
            'bv':'0ea2f265e69dc7094ed5f0b64ef39e0b',
            'doctype':'json',
            'version':'2.1',
            'keyform':'fanyi.web',
            'action':'FY_BY_REALTlME'
        }
        Form_data['i']=str(userInput)

        response = requests.post(url,data = Form_data)
        youdaofanyi = json.loads(response.text)
        fanyi = youdaofanyi['translateResult'][0][0]['tgt']
        result = {}
        result['userInput']=userInput
        result['result']=fanyi
        context = {'result':result}
        print(context)
        return render(request,'word/translate.html',context)

def search(request):
    # 提取用户提交得数据
    userInput = request.POST.get('userInput')
    # print(userInput)
    if userInput is not None:
        searchResult = Word.objects.get(spell = str(userInput))
        # print(searchResult.example)
        context = {'userSearch':searchResult}
        return render(request,'word/search.html',context)
    else:
        return render(request,'word/search.html')

def deeplearning(request):
    # 取出所有的 word
    # try:
    #     word_list = WordColumn.objects.get(id=1)
    # except :
    #     print("查询失败")
    # 每页显示10个单词
    # paginator = Paginator(word_list, 3)
    # 获取 url 中的页码
    # page = request.GET.get('page')
    # 将相应的页码返回给words
    # words = paginator.get_page(page)
    # 返回的对象做成字典
    # context = {'words':words}
    # 载入模板 将 context返回
    return HttpResponse("暂不支持外键查询")

def insert(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = UserInsert(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new = article_post_form.save(commit=False)
            # 将新文章保存到数据库中
            new.save()
            # 完成后返回到文章列表
            return redirect('dict:word_list')
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = UserInsert()
        # 赋值上下文
        context = { 'article_post_form': article_post_form }
        # 返回模板
        return render(request, 'word/insert.html', context)

def order(request):
    # 取出所有的 word
    word_list = Word.objects.filter(spell__contains='b')
    # 每页显示10个单词
    paginator = Paginator(word_list, 3)
    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将相应的页码返回给words
    words = paginator.get_page(page)
    # 返回的对象做成字典
    context = {'words':words}
    # 载入模板 将 context返回
    return render(request,'word/list.html',context)

workbook/templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css">
    <style>
        .jumbotron{
            background-image: url('{% static 'img/nav.png' %}');
        }
    </style>
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>
</body>
</html>

workbook/templates/footer.html
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 fixed-bottom" style="background-color:#f9f9fb">
    <div class="container">
        <p class="m-0 text-center" style="text-color: #333;">Copyright &copy; Madeby ccy</p>
    </div>
</footer>

workbook/templates/header.html
<style>
  .display-4{
    margin-top: 0;
    /* padding-top: 50px; */
    margin-bottom: 15px;
    font-size: 50px;
    font-weight: 400;
    color: #fff;
    text-shadow: 0 0 25px rgba(51,88,104,.5);
    letter-spacing: .1em;
  }
</style>
<div class="jumbotron jumbotron-fluid" style="background-color: #45abf3;height: 250px;">
    <div class="container">
        <!-- 头部 -->
        <h1 class="display-4 text-center">芒果词典</h1>
        <!-- <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p> -->
        <!-- 导航 -->
        <br>
        <br>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dict:word_list' %} ">首页</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dict:translate' %} ">翻译</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dict:search' %} ">搜索</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dict:insert' %} ">增加</a></li>
            <!-- <li class="breadcrumb-item"><a href="#">拍照翻译</a></li>
            <li class="breadcrumb-item"><a href="#">文档翻译</a></li> -->
          </ol>
        </nav>
    </div>
</div>

workbook/templates/word/deeplearning.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  首页
{% endblock title %}

{% block content %}
<div class="container">
  <!-- 单词显示区 -->
  <div class="row">
    <div class="col-sm-4">
        <!-- <div class="card" style="width: 18rem;">
            <img src="" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">姓名：陈郊</h5>
              <p class="card-text">简介：五月，小巷微凉</p>
            </div>
        </div> -->
        <!-- 分类 -->
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">分类专栏</h5>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">英语六级词汇</li>
                <li class="list-group-item">英语四级词汇</li>
                <li class="list-group-item">Python相关词汇</li>
                <li class="list-group-item">
                  <a href="{% url 'dict:deeplearning' %} ">深度学习相关词汇</a>
                </li>
              </ul>
              <a href="#" class="card-link">更多</a>
            </div>
        </div>
    </div>

    <div class="col-sm-8">
        <!-- main部分 头部导航 -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">单词清单<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    排序方式
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">A开头</a>
                    <a class="dropdown-item"><a href="{% url 'dict:order' %} ">B开头</a></a>
                  </div>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="输入内容" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
              </form>
            </div>
        </nav>
        <br>
        <!-- main部分 列表 -->
        {% for word in words %}
        <div class="card">
          <div class="card-header">
            <h5>{{ word.spell }}</h5>
          </div>
          <div class="card-body">
            <!-- <p class="card-text"><span class="badge badge-secondary">词性：&nbsp&nbsp{{ word.nature }}</span></p> -->
            <h6 class="card-title">中文：&nbsp&nbsp{{ word.translation }}</h6>
            <p class="card-text">例句：&nbsp&nbsp{{ word.example }}</p>
            <a href="{% url 'dict:word_detail' word.id %} " class="btn btn-primary">更多细节</a>
          </div>
        </div>
        <!-- <ul class="list-unstyled">
            <li class="media">
              <div class="media-body">
                <h5 class="mt-0 mb-1">{{ word.spell }}</h5>
                <h6><span class="badge badge-primary">词性：{{ word.nature }}</span></h6>
                <h6><span class="badge badge-info">中文：</span>&nbsp&nbsp{{ word.translation }} </h6>
                <h6><span class="badge badge-success">例句：</span></h6>
              </div>
            </li>
        </ul> -->
        {% endfor %}

        <!-- main部分 分页 -->
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if words.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1">Privious</a>
              <!-- <a href="?page={{ words.previous_page_number }}">{{ words.previous_page_number }}</a> -->
            </li>
            {% endif %}

            <!-- 当前页面 -->
            <li class="page-item">
              <a class="page-link" href="#">{{ words.number }}</a>
            </li>

            {% if words.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ words.next_page_number }}">Next</a>
              <!-- <a href="?page={{ words.paginator.num_pages }}">{{ words.paginator.num_pages }}</a> -->
            </li>
            {% endif %}
          </ul>
        </nav>
    </div>
  </div>
{% endblock content %}

workbook/templates/word/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    单词详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 单词详情 -->
<div class="container">
    <div class="row">
        <!-- 单词拼写 -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active" aria-current="page">
                  <a href="{% url 'dict:word_list' %}">返回首页</a>
              </li>
            </ol>
        </nav>
        <!-- <div class="row">
            {% if word.column %}
                <button type="button" 
                    class="btn btn-sm
                        {% if word.column.title == 'deeplearning' %}
                        btn-primary
                        {% elif word.column.title == '四级词汇' %}
                        btn-secondary
                        {% elif word.column.title == '六级词汇' %}
                        btn-success
                        {% elif word.column.title == 'Python相关' %}
                        btn-danger
                        {% endif %}
                    "
                >
                {{ word.column.title }}
                </button>
        {% endif %}
        </div> -->
        <h1 class="col-12 mt-4 mb-4" style="background-color: #45abf3;">{{ word.spell }}</h1>
        <div class="col-12 alert alert-success">
            <h5>中文：&nbsp&nbsp{{ word.translation }}</h5>
            <h5>例句：&nbsp&nbsp{{ word.example }}</h5>
        </div>
        
    </div>
</div>

{% endblock content %}

workbook/templates/word/insert.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  首页
{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
      <div class="col-12">
          <br>
          <!-- 提交的表单 -->
          <form method="post" action=".">
              <!-- Django中需要POST数据的地方都必须有csrf_token -->
              {% csrf_token %}
              <!-- spell -->
              <div class="form-group">
                  <!-- 标签 -->
                  <label for="spell">拼写</label>
                  <!-- 文本框 -->
                  <input type="text" class="form-control" id="spell" name="spell">
              </div>
              <!-- past -->
              <div class="form-group">
                <!-- 标签 -->
                <label for="title">过去式</label>
                <!-- 文本框 -->
                <input type="text" class="form-control" id="past" name="past">
              </div>

              <div class="form-group">
                <!-- 标签 -->
                <label for="title">过去分词</label>
                <!-- 文本框 -->
                <input type="text" class="form-control" id="pasted" name="pasted">
              </div>

              <div class="form-group">
                <!-- 标签 -->
                <label for="title">现在分词</label>
                <!-- 文本框 -->
                <input type="text" class="form-control" id="nowing" name="nowing">
              </div>

              <div class="form-group">
                <!-- 标签 -->
                <label for="title">复数</label>
                <!-- 文本框 -->
                <input type="text" class="form-control" id="fushu" name="fushu">
              </div>

              <div class="form-group">
                <!-- 标签 -->
                <label for="title">词性-中文翻译</label>
                <!-- 文本框 -->
                <input type="text" class="form-control" id="translation" name="translation">
              </div>
              
              <div class="form-group">
                  <label for="body">例句</label>
                  <!-- 文本区域 -->
                  <textarea type="text" class="form-control" id="example" name="example" rows="12"></textarea>
              </div>
              <!-- 提交按钮 -->
              <button type="submit" class="btn btn-primary">完成</button>
          </form>
      </div>
  </div>
</div>
{% endblock content %}

workbook/templates/word/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  首页
{% endblock title %}

{% block content %}
<div class="container">
  <!-- 单词显示区 -->
  <div class="row">
    <div class="col-sm-4">
        <!-- <div class="card" style="width: 18rem;">
            <img src="" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">姓名：陈郊</h5>
              <p class="card-text">简介：五月，小巷微凉</p>
            </div>
        </div> -->
        <!-- 分类 -->
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">分类专栏</h5>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <a href="{% url 'dict:deeplearning' %} ">深度学习相关词汇</a>
                </li>
                <li class="list-group-item">
                  <a href="{% url 'dict:deeplearning' %} ">英语六级</a>
                </li>
                <li class="list-group-item">
                  <a href="{% url 'dict:deeplearning' %} ">英语四级</a>
                </li>
                <li class="list-group-item">
                  <a href="{% url 'dict:deeplearning' %} ">Python相关</a>
                </li>
              </ul>
              <a href="#" class="card-link">更多</a>
            </div>
        </div>
    </div>

    <div class="col-sm-8">
        <!-- main部分 头部导航 -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">单词清单<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    排序方式
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">A开头</a>
                    <a class="dropdown-item" href="{% url 'dict:order' %}">B开头</a>
                  </div>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="输入内容" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
              </form>
            </div>
        </nav>
        <br>
        <!-- main部分 列表 -->
        {% for word in words %}
        <div class="card">
          <div class="card-header">
            <h5>{{ word.spell }}</h5>
          </div>
          <div class="card-body">
            <!-- <p class="card-text"><span class="badge badge-secondary">词性：&nbsp&nbsp{{ word.nature }}</span></p> -->
            <h6 class="card-title">中文：&nbsp&nbsp{{ word.translation }}</h6>
            <p class="card-text">例句：&nbsp&nbsp{{ word.example }}</p>
            <a href="{% url 'dict:word_detail' word.id %} " class="btn btn-primary">更多细节</a>
          </div>
        </div>
        <!-- <ul class="list-unstyled">
            <li class="media">
              <div class="media-body">
                <h5 class="mt-0 mb-1">{{ word.spell }}</h5>
                <h6><span class="badge badge-primary">词性：{{ word.nature }}</span></h6>
                <h6><span class="badge badge-info">中文：</span>&nbsp&nbsp{{ word.translation }} </h6>
                <h6><span class="badge badge-success">例句：</span></h6>
              </div>
            </li>
        </ul> -->
        {% endfor %}

        <!-- main部分 分页 -->
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if words.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1">Privious</a>
              <!-- <a href="?page={{ words.previous_page_number }}">{{ words.previous_page_number }}</a> -->
            </li>
            {% endif %}

            <!-- 当前页面 -->
            <li class="page-item">
              <a class="page-link" href="#">{{ words.number }}</a>
            </li>

            {% if words.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ words.next_page_number }}">Next</a>
              <!-- <a href="?page={{ words.paginator.num_pages }}">{{ words.paginator.num_pages }}</a> -->
            </li>
            {% endif %}
          </ul>
        </nav>
    </div>
  </div>
{% endblock content %}

workbook/templates/word/order.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  首页
{% endblock title %}

{% block content %}
<div class="container">
  <!-- 单词显示区 -->
  <div class="row">
    <div class="col-sm-4">
        <!-- <div class="card" style="width: 18rem;">
            <img src="" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">姓名：陈郊</h5>
              <p class="card-text">简介：五月，小巷微凉</p>
            </div>
        </div> -->
        <!-- 分类 -->
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">分类专栏</h5>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">英语六级词汇</li>
                <li class="list-group-item">英语四级词汇</li>
                <li class="list-group-item">Python相关词汇</li>
                <li class="list-group-item">
                  <a href="{% url 'dict:deeplearning' %} ">深度学习相关词汇</a>
                </li>
              </ul>
              <a href="#" class="card-link">更多</a>
            </div>
        </div>
    </div>

    <div class="col-sm-8">
        <!-- main部分 头部导航 -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">单词清单<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    排序方式
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">A开头</a>
                    <a class="dropdown-item"><a href="{% url 'dict:order' %} ">B开头</a></a>
                  </div>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="输入内容" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
              </form>
            </div>
        </nav>
        <br>
        <!-- main部分 列表 -->
        {% for word in words %}
        <div class="card">
          <div class="card-header">
            <h5>{{ word.spell }}</h5>
          </div>
          <div class="card-body">
            <!-- <p class="card-text"><span class="badge badge-secondary">词性：&nbsp&nbsp{{ word.nature }}</span></p> -->
            <h6 class="card-title">中文：&nbsp&nbsp{{ word.translation }}</h6>
            <p class="card-text">例句：&nbsp&nbsp{{ word.example }}</p>
            <a href="{% url 'dict:word_detail' word.id %} " class="btn btn-primary">更多细节</a>
          </div>
        </div>
        <!-- <ul class="list-unstyled">
            <li class="media">
              <div class="media-body">
                <h5 class="mt-0 mb-1">{{ word.spell }}</h5>
                <h6><span class="badge badge-primary">词性：{{ word.nature }}</span></h6>
                <h6><span class="badge badge-info">中文：</span>&nbsp&nbsp{{ word.translation }} </h6>
                <h6><span class="badge badge-success">例句：</span></h6>
              </div>
            </li>
        </ul> -->
        {% endfor %}

        <!-- main部分 分页 -->
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if words.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1">Privious</a>
              <!-- <a href="?page={{ words.previous_page_number }}">{{ words.previous_page_number }}</a> -->
            </li>
            {% endif %}

            <!-- 当前页面 -->
            <li class="page-item">
              <a class="page-link" href="#">{{ words.number }}</a>
            </li>

            {% if words.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ words.next_page_number }}">Next</a>
              <!-- <a href="?page={{ words.paginator.num_pages }}">{{ words.paginator.num_pages }}</a> -->
            </li>
            {% endif %}
          </ul>
        </nav>
    </div>
  </div>
{% endblock content %}

workbook/templates/word/search.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  首页
{% endblock title %}

{% block content %}
<div class="container">
    <!-- 输入区 -->
    <form action="" method="POST">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="search" id="userInput" name='userInput'>
            <div class="input-group-append">
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn">提交</button>
    </form>

    <form action="">
    <div class="form-group">
        <label for="exampleFormControlTextarea1">搜索结果</label>
        <textarea class="form-control"  rows="5">{{ userSearch.example }}</textarea>
    </div>
    </form>
</div>
{% endblock content %}

workbook/templates/word/translate.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  首页
{% endblock title %}

{% block content %}
<div class="container">
  <!-- 翻译区 -->
  <!-- 输入区 -->
  <div class="row">
    <div class="col-sm-6">
      <form method="post" action=".">
        {% csrf_token %}
        <div class="form-group">
          <div class="row">
            <div class="col-3"><label for="exampleFormControlTextarea1">输入中文</label></div>
            <div class="col-2 offset-md-7"><button type="submit" class="btn btn-primary btn-sm">提交</button></div>
          </div>
          <textarea type='text' class="form-control" id="userInput" name='userInput' rows="5">{{result.userInput}}</textarea>
        </div>
      </form>
    </div>
    <!-- 结果返回区 -->
    <div class="col-sm-6">
      <form action="">
        <div class="form-group">
          <label for="exampleFormControlTextarea1">翻译结果</label>
          <textarea class="form-control"  rows="5">{{ result.result }}</textarea>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}